version: "3.9"

services:
  db:
    image: percona/percona-server:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuserpass
  nginx:
    depends_on:
      - app1
      - app2
    build: ./nginx
    ports: 
    - "8080:80"
  app1:
    depends_on:
      - db
    build: ./app1
    ports: 
    - "5001:5000"
  app2:
    depends_on:
      - db
    build: ./app2
    ports: 
    - "5002:5000"
volumes:
  db_data: {}
# networks:
#   default:
#     driver: bridge